name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Ensure this matches your project's Python version

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
      shell: pwsh

    - name: Add Poetry to PATH
      run: |
        $poetryPath = "$env:USERPROFILE\AppData\Roaming\Python\Scripts"
        echo "$poetryPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: pwsh

    - name: Verify Poetry Installation
      run: |
        poetry --version
      shell: pwsh

    - name: Install Dependencies
      run: |
        poetry install --no-interaction --no-ansi
      shell: pwsh

    - name: Add PyInstaller as Development Dependency
      run: |
        poetry add --group dev pyinstaller
      shell: pwsh

    - name: Build Executable with PyInstaller
      run: |
        poetry run pyinstaller main.py --onefile --windowed --icon=path\to\icon.ico
      shell: pwsh

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TournamentSessionAnalyzer
        path: dist/TournamentSessionAnalyzer.exe